import {Metadata} from 'next'

export const metadata: Metadata = {
  title: {
    // if use absolute
    absolute: "SEO-Nextjs-Absolute-Tutorial-Prabhat",
    default: "Next.js 14 Tutorial- Prabhat-SEo",
    template: "%s | Prabhat Next Tutorial-SEO",
  },
  // title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body>
        <header style={{
          backgroundColor: 'lightblue',
          padding: '1rem',
        }}>
          <p>Header</p>
        </header>
        
        {children}
        <footer style={{
          backgroundColor: 'ghostwhite',
          padding: '1rem',
        }}>
          <p>Footer</p>
        </footer>
      
      
      </body>
    </html>
  )
}
